
FROM node:8.4
# Create app directory
RUN mkdir /app
WORKDIR /app
# Install app dependencies
COPY package.json package-lock.json ./

RUN npm install
# Bundle app source
COPY . /app
EXPOSE 3000
CMD [ "npm", "start" ]